myproject/core/urls.py
from django.conf.urls import url
from myproject.core import views as v


urlpatterns = [
    url(r'^$', v.index, name='index'),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout
from myproject.core import views as v


urlpatterns = [
    # url(r'login/', v.login, name='login'),
    url(
        r'^logout/$',
        logout,
        {'next_page': settings.LOGOUT_REDIRECT_URL},
        name='logout'
    ),
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models

# Create your models here.

myproject/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    class Meta:
        model = User

myproject/core/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from .forms import LoginForm


def index(request):
    form = LoginForm()
    if request.is_ajax() and request.method == 'POST':
        form = LoginForm(request, request.POST)
        user = None
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            response = {'status': 'logged'}
            return JsonResponse(response)
        else:
            response = {'status': 'error'}
            return JsonResponse(response)
            # return HttpResponse('Usuário inválido')
    ctx = {'form': form}
    return render(request, 'index.html', ctx)

myproject/core/templates/base.html
<html>
<head>

  {% block title %}
      <title>Login | Ajax</title>
  {% endblock title %}

  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <link rel="icon" href="http://s3.amazonaws.com/snaaakes-static/img/colophon/django.png">

  <!-- Latest JQuery -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
    body {
      padding-top: 70px;
    }
  </style>

</head>

<body>

  {% include "nav.html" %}

  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

  {% block js %}
    
  {% endblock js %}

</body>
</html>

myproject/core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}
<div class="jumbotron">
    <h1>Bem vindo ao site!</h1>
    <p>Este é um exemplo de como fazer Login via Ajax.</p>
    {% if user.is_authenticated %}
      <p>Olá {{ user }}</p>
       <a href="{% url 'logout' %}" class="btn btn-default">Sair</a>
    {% else %}
       <a href="#LoginModal" role="button" data-toggle="modal" class="btn btn-default">Login</a>
    {% endif %}

    
    <div class="modal fade" id="LoginModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
             
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
              ×
            </button>
            <h4 class="modal-title" id="myModalLabel">
              Login
            </h4>
          </div>
          <form id="loginForm" action="." method="POST">
            <div class="modal-body">
              {% csrf_token %}
              {{ form|bootstrap }}
            </div>
            <div class="modal-footer">
              <input type="submit" class="btn btn-primary" value="Acessar" />
            </div>
          </form>
        </div>
        
      </div>
      
    </div>
    
</div>

{% endblock content %}


{% block js %}

<script src="{% static 'js/django-ajax-setup.js' %}"></script>

<!-- Login with Ajax -->
<script>
  $('#loginForm').on('submit', function(e) {
    $.ajax({
      url: this.action,
      type: "POST",
      dataType: 'json',
      data: $(this).serialize(),
      success: function(response) {
        location.reload();
      },
      error: function(response) {
        console.log(response);
      },
    });
    e.preventDefault()
  });

</script>

{% endblock js %}

myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#LoginModal" role="button" data-toggle="modal">Login</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </div>
  </div>
</div>